spring:
  datasource:
    url: jdbc:mysql://118.25.49.166:20000/vlink_platform?useUnicode=true
    username: root
    password: k65W15uIQo0qs1IG
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari: # https://github.com/brettwooldridge/HikariCP (uses milliseconds for all time values)
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000

  redis:
    host: 49.235.136.189
    port: 9999
    database: 1
    password: password!!!###
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
      shutdown-timeout: 100 # 关闭超时时间

logging:
  level:
    com:
      vlink:
        cloud:
          auth:
            dao: debug

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@122.224.34.237:9991/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@122.224.34.138:9992/eureka/
      lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
      lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除


alarm:
  open-notice: true
  project-name: ${spring.application.name}
  default-notice: zqf
  token-limit-per-minute: 18
  ding-talk-web-hook-dev-token:
    - 442a4d925b5602b682066e81ea51c2ebbffdc73a20a6654607dd6b615b6cd3b4
    - ea48895fdb3b04317f925f0532d35eabc57333fbec2de5450e887ca1d54c9e5a
  ding-talk-web-hook-prod-token:
    - 442a4d925b5602b682066e81ea51c2ebbffdc73a20a6654607dd6b615b6cd3b4
    - ea48895fdb3b04317f925f0532d35eabc57333fbec2de5450e887ca1d54c9e5a
  ding-talk-notice:
    zqf: 13677173510
    ct: 18349203693

sms:
  name: 【授权】