server:
  port: 9000
spring:
  application:
    name: z-gateway
  security: #安全用户和密码
    user:
      name: z201
      password: z201!
      roles:
        - ADMIN
  profiles:
    active: dev1
#  cloud:
#    gateway:
#      default-filters:
#      - name: Retry
#        args:
#          retries: 3
#          statuses: BAD_GATEWAY
#      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
#      - name: RequestRateLimiter
#        args:
#          redis-rate-limiter.replenishRate: 5    #流速 每秒
#          redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
#          rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
#          key-resolver: "#{@apiKeyResolver}"           #SPEL表达式去的对应的bean

#网关白名单，无需要签权url
vlink:
  gateway:
    oauth2-jwt-sign-key: api.z201.cn
    ignore-url-start-with: /authorization

logging:
  config: classpath:logback.xml

alarm:
  open-notice: true
  project-name: ${spring.application.name}
  default-notice: zqf
  token-limit-per-minute: 18
  ding-talk-web-hook-dev-token:
    - 442a4d925b5602b682066e81ea51c2ebbffdc73a20a6654607dd6b615b6cd3b4
    - ea48895fdb3b04317f925f0532d35eabc57333fbec2de5450e887ca1d54c9e5a
  ding-talk-web-hook-prod-token:
    - 442a4d925b5602b682066e81ea51c2ebbffdc73a20a6654607dd6b615b6cd3b4
    - ea48895fdb3b04317f925f0532d35eabc57333fbec2de5450e887ca1d54c9e5a
  ding-talk-notice:
    zqf: 13677173510
